app/post/views.py
# app/posts/views.py
import datetime
import os

from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
from sqlalchemy import desc
from werkzeug.utils import secure_filename

from ..forms import PostForm
from ..models import db, Post, Category, Tag

posts_bp = Blueprint('posts', __name__)


@posts_bp.route('/posts', methods=['GET'])
def posts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(desc(Post.created)).paginate(page=page, per_page=5, error_out=False)
    return render_template('posts/posts.html', posts=posts)


@posts_bp.route('/add_post', methods=['GET', 'POST'])
@login_required
def add_post():
    form = PostForm()
    categories = Category.query.all()
    form.category.choices = [(category.id, category.name) for category in categories]

    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            text=form.text.data,
            user_id=current_user.id,
            category_id=form.category.data,
            type=form.type.data
        )

        tags = Tag.query.filter(Tag.id.in_(form.tags.data)).all()
        post.tags.extend(tags)

        db.session.add(post)
        db.session.commit()

        if form.image.data:
            new_file_name = f"{post.id}.png"
            file_path = os.path.join('app/static/post_images', new_file_name)
            form.image.data.save(file_path)
            post.image = new_file_name

        db.session.commit()

        flash('Post created successfully!', 'success')
        return redirect(url_for('posts.posts'))

    return render_template('posts/add_post.html', form=form)


@posts_bp.route('/my_posts', methods=['GET'])
@login_required
def my_posts():
    page = request.args.get('page', 1, type=int)
    user_posts = Post.query.filter_by(user_id=current_user.id).order_by(desc(Post.created)).paginate(page=page, per_page=5, error_out=False)
    form = PostForm()
    return render_template('posts/my_posts.html', user_posts=user_posts, form=form)


@posts_bp.route('/edit_post/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    form = PostForm(obj=post)
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]

    post_tags = [tag.id for tag in post.tags]

    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        post.type = form.type.data
        post.category_id = form.category.data
        post.created = datetime.datetime.utcnow()

        tags = Tag.query.filter(Tag.id.in_(form.tags.data)).all()
        post.tags = tags

        if form.image.data:
            _, file_extension = os.path.splitext(form.image.data.filename)
            new_file_name = secure_filename(f"{post.id}.png")
            new_file_path = os.path.join('app/static/post_images', new_file_name)
            form.image.data.save(new_file_path)
            post.image = new_file_name

        db.session.commit()
        flash('Post updated successfully!', 'success')
        return redirect(url_for('posts.my_posts'))

    return render_template('posts/edit_posts.html', form=form, post=post)


@posts_bp.route('/delete_post/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_post(id):
    post = Post.query.get_or_404(id)
    if current_user.id != post.user_id:
        flash('You do not have permission to delete this post.', 'danger')
        return redirect(url_for('posts.my_posts'))

    db.session.delete(post)
    db.session.commit()

    flash('Post deleted successfully!', 'success')
    return redirect(url_for('posts.my_posts'))

app/templates/posts/add_post.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="mt-4">Add Post</h1>
    <br>
    <form method="POST" action="{{ url_for('posts.add_post') }}" class="mt-3" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <div class="mb-3">
            <label for="title" class="form-label">Title:</label>
            {{ form.title(class="form-control") }}
        </div>

        <div class="mb-3">
            <label for="text" class="form-label">Text:</label>
            {{ form.text(class="form-control") }}
        </div>

        <div class="mb-3">
            <label for="image" class="form-label">Image:</label>
            {{ form.image(class="form-control") }}
        </div>

        <div class="mb-3">
            <label for="type" class="form-label">Type:</label>
            {{ form.type(class="form-control") }}
        </div>

        <div class="mb-3">
            <label for="category" class="form-label">Category:</label>
            {{ form.category(class="form-control") }}
        </div>

        <div class="mb-3">
            <label for="category" class="form-label">Tags:</label>
            <div class="input-group">
                <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    Select Tags
                </button>
                <div class="dropdown-menu" style="max-height: 200px; overflow-y: auto;">
                    {% for tag_id, tag_name in form.tags.choices %}
                        <div class="dropdown-item">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="tag{{ tag_id }}" name="tags"
                                       value="{{ tag_id }}">
                                <label class="form-check-label" for="tag{{ tag_id }}">{{ tag_name }}</label>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <button type="submit" name="submit" value="Submit" class="btn btn-success">Submit</button>
    </form>
    <br><br>
</div>
{% endblock %}

app/templates/posts/edit_posts.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Edit Post</h1>
    <br>
    <form method="POST" action="{{ url_for('posts.edit_post', id=post.id) }}" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <div class="form-group">
            <label for="title">Title:</label>
            {{ form.title(class="form-control") }}
        </div>

        <div class="form-group">
            <label for="text">Text:</label>
            {{ form.text(class="form-control") }}
        </div>

        <div class="form-group">
            <label for="image">Image:</label>
            {{ form.image(class="form-control") }}
        </div>

        <div class="form-group">
            <label for="type">Type:</label>
            {{ form.type(class="form-control") }}
        </div>

        <div class="form-group">
            <label for="category">Category:</label>
            {{ form.category(class="form-control") }}
        </div>

        <div class="form-group mr-3">
            <label for="category">Tags:</label>

            <div class="input-group">
                <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    Select Tags
                </button>
                <div class="dropdown-menu" style="max-height: 200px; overflow-y: auto;">
                    {% for tag_id, tag_name in form.tags.choices %}
                    <div class="dropdown-item">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="tag{{ tag_id }}" name="tags"
                                   value="{{ tag_id }}"
                                   {% if tag_id in post.tags|map(attribute='id' ) %}checked{% endif %}>
                            <label class="form-check-label" for="tag{{ tag_id }}">{{ tag_name }}</label>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        {{ form.submit(class="btn btn-success") }}
    </form>
</div>
{% endblock %}

app/templates/posts/my_posts.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">My Posts</h1>
    <br>
    <ul class="list-group">
        {% for post in user_posts.items %}
        <li class="list-group-item mb-3">
            {% with user = post.get_user() %}
            <div class="d-flex align-items-center">
                <img src="{{ url_for('static', filename='../static/profile_images/' + user.image_file) }}"
                     class="rounded-circle" alt="User Avatar" width="32" height="32">
                <span class="ml-2">{{ user.username }}</span>
            </div>
            {% endwith %}

            <h3 class="my-2">{{ post.title }}</h3>
            <p class="mb-2">{{ post.text }}</p>

            {% if post.image %}
            <div class="text-center">
                <img src="{{ url_for('static', filename='../static/post_images/' + post.image) }}"
                     class="img-fluid mb-2" alt="Post Image">
            </div>
            {% endif %}


            <p class="mb-2">Category: {{ post.category.name }}</p>
            <p class="mb-2">Type: {{ post.type }}</p>

            {% if post.tags %}
            <p>Tags:
                {% for tag in post.tags %}
                <span class="badge badge-primary">{{ tag.name }}</span>
                {% endfor %}
            </p>
            {% endif %}

            <p class="mb-2">Created: {{ post.created }}</p>

            <div class="btn-group" role="group" aria-label="Post Actions">
                <a href="{{ url_for('posts.edit_post', id=post.id) }}" class="btn btn-warning btn-sm">Edit</a>
                <a href="{{ url_for('posts.delete_post', id=post.id) }}"
                   onclick="return confirm('Are you sure you want to delete this post?');"
                   class="btn btn-danger btn-sm">Delete</a>
            </div>
        </li>
        {% endfor %}
    </ul>
    <br>
    <nav aria-label="Page navigation" class="d-flex justify-content-center">
        <ul class="pagination mt-4">
            {%- for page_num in user_posts.iter_pages() %}
              {% if page_num %}
                {% if user_posts.page == page_num %}
                  <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ page_num }}<span class="visually-hidden"></span></span>
                  </li>
                {% else %}
                  <li class="page-item"><a class="page-link" href="{{ url_for('posts.my_posts', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
              {% else %}
                <li class="page-item disabled"><span class="page-link">...</span></li>
              {% endif %}
            {%- endfor %}
        </ul>
    </nav>
    <br>
    <br>
</div>
{% endblock %}

app/templates/posts/posts.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Posts</h1>
    <br>
    <ul class="list-group">
        {% for post in posts %}
        <li class="list-group-item mb-3">
            {% with user = post.get_user() %}
            <div class="d-flex align-items-center">
                <img src="{{ url_for('static', filename='../static/profile_images/' + user.image_file) }}"
                     class="rounded-circle" alt="User Avatar" width="32" height="32">
                <span class="ml-2">{{ user.username }}</span>
            </div>
            {% endwith %}

            <h3 class="my-2">{{ post.title }}</h3>
            <p class="mb-2">{{ post.text }}</p>

            {% if post.image %}
            <div class="text-center">
                <img src="{{ url_for('static', filename='../static/post_images/' + post.image) }}"
                     class="img-fluid mb-2" alt="Post Image">
            </div>
            {% endif %}

            <p class="mb-2">Category: {{ post.category.name }}</p>
            <p class="mb-2">Type: {{ post.type }}</p>

            {% if post.tags %}
            <p>Tags:
                {% for tag in post.tags %}
                <span class="badge badge-primary">{{ tag.name }}</span>
                {% endfor %}
            </p>
            {% endif %}

            <p class="mb-2">Created: {{ post.created }}</p>
        </li>
        {% endfor %}
    </ul>
    <br>
    <nav aria-label="Page navigation" class="d-flex justify-content-center">
        <ul class="pagination mt-4">
            {%- for page_num in posts.iter_pages() %}
              {% if page_num %}
                {% if posts.page == page_num %}
                  <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ page_num }}<span class="visually-hidden"></span></span>
                  </li>
                {% else %}
                  <li class="page-item"><a class="page-link" href="{{ url_for('posts.posts', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
              {% else %}
                <li class="page-item disabled"><span class="page-link">...</span></li>
              {% endif %}
            {%- endfor %}
        </ul>
    </nav>
    <br>
    <br>
</div>
{% endblock %}